version: "3"

services: 
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - "8000:8000"
    links:
      - mongo
    volumes: 
      - .:/usr/src/app
  
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27017"
    volumes:
      - ./mongo/data:/data/db